export enum LABELS {
	COMMENTS = 'Комментарии',
	LEAVE_YOUR_EMAIL = 'Оставьте свой email и мы отправим туда данные о Вашей записи',
	EMAIL = 'Email',
	PHONE = 'Телефон',
	NAME = 'Имя',
	SURNAME = 'Фамилия',
	DATE = 'Дата:',
	START_TIME = 'Время начала:',
	SELECTED_SERVICE = 'Выбранная услуга:',
	MASTER_NAME = 'Имя мастера:',
	ORDER_CREATED = 'Запись успешно создана',
	MAIN_PAGE_TITLE = 'Система онлайн записи в студию маникюра Анастасии Крень',
	MAIN_PAGE_SUBTITLE = 'Удобный способ самостоятельного бронирования, доступный 24/7.',
}
